<?php

namespace AppBundle\Repository;

/**
 * GameEventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameEventTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
