<?php

namespace AppBundle\Repository;

/**
 * GameEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameEventRepository extends \Doctrine\ORM\EntityRepository
{
}
