<?php

namespace AppBundle\Repository;

/**
 * GameFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
